version: '2'

services:
 docker-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=poc_restful_api
      - MYSQL_PASSWORD=root

 restful-api-service:
    restart: always
    build: ./src/main/docker
    image: springio/poc-restful-api
    depends_on:
      - docker-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=poc_restful_api
      - DATABASE_PORT=3306