version: '2'

services:
# nginx:
#    container_name: nginx-service
#    image: nginx:1.13
#    restart: always
#    ports:
#      - 80:80
#    volumes:
#      - ./nginx/conf.d:/etc/nginx/conf.d

 mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=poc_restful_api
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"

 restful-api-service:
    container_name: service-restful-api
    restart: always
    #build: ./src/main/docker
    #command: mvn clean package docker:build -DskipTests=true
    image: trungung/poc-restful-api
    depends_on:
      - mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=poc_restful_api
      - DATABASE_PORT=3306