# ===================================================================
# Spring Boot configuration for the Staging profile.
# ===================================================================

welcome:
  message: Welcome message from property file! Welcome to ${app.name} in STAGING

spring:
  profiles: staging
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/poc_restful_api?autoReconnect=true&useSSL=false
    username: root
    password: root
    driver: com.mysql.jdbc.Driver
    initialize: true # Populate the database using 'data.sql'.

  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate.ddl-auto: create
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false

# Port configuration
server:
  port: 8080
  contextPath: /api
security:
  user:
  password: weak

# Logging aspect configuration
logging-aspect:
  enable: true

# Security configuration
jwt:
  app-name: Poc-Restful-API
  secret-key: a4f2aa63cdc8dcaa5e92ea8fd19fca749b61c343
  expires-in: 360000 #second
  token-prefix: Bearer

  # Token invitation
  invitation-expires-in: 86400 #second

  # Token reset password
  reset-password-expires-in: 1800 #second