# ===================================================================
# Spring Boot configuration for the Staging profile.
# ===================================================================

welcome:
  message: Welcome message from property file! Welcome to ${app.name} in STAGING

basic:
  message: Dynamic Message in STAGING

spring:
  profiles: staging
  datasource:
    url: jdbc:mysql://mysql:3306/poc_restful_api?autoReconnect=true&useSSL=false
    username: root
    password: root
    driver: com.mysql.jdbc.Driver
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update)


# Logging aspect configuration
logging-aspect:
  enable: true

# Security configuration
jwt:
  app-name: Poc-Restful-API
  secret-key: a4f2aa63cdc8dcaa5e92ea8fd19fca749b61c343
  expires-in: 360000 #second
  token-prefix: Bearer

  # Token invitation
  invitation-expires-in: 86400 #second

  # Token reset password
  reset-password-expires-in: 1800 #second